<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DashboardLogin.aspx.cs" Inherits="Smarter_HRIS.DashboardLogin" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" class="lockscreen">
<head runat="server">
    <title>Dashboard Login</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport' />
    <!-- bootstrap 3.0.2 -->
    <link href="css1/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- font Awesome -->
    <link href="css1/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="css1/AdminLTE.css" rel="stylesheet" type="text/css" />

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
    <form id="form1" runat="server">
        <div>

            <!-- Automatic element centering using js -->
            <div class="center">

                <div>
                    <%--<img src="Images/productERP.png" />--%>
                    <img src="Images/SmartHRIS0.png" />
                </div>

                <div class="headline text-center" id="time">
                    <!-- Time auto generated by js -->
                </div>
                <!-- /.headline -->

                <div class="headline1 text-center">
                    
                </div>
                <!-- User name -->
                <div class="lockscreen-name">Dashboard LogIn</div>

                <!-- START LOCK SCREEN ITEM -->
                <div class="lockscreen-item">
                    <!-- lockscreen image -->
                    <div class="lockscreen-image">
                        <img src="img/avatar5.png" alt="user image" />
                    </div>
                    <!-- /.lockscreen-image -->

                    <!-- lockscreen credentials (contains the form) -->
                    <div class="lockscreen-credentials">

                        <div class="input-group">
                            <input type="text" runat="server" id="txtUserName" class="form-control" placeholder="username" />
                            <div class="input-group-btn">
                                <%--<button class="btn btn-flat"><i class="fa fa-arrow-right text-muted"></i></button>--%>
                            </div>
                        </div>

                        <div class="input-group">
                            <input type="password" runat="server" id="txtPassword" class="form-control" placeholder="password" />
                            <div class="input-group-btn">
                                <%--<button class="btn btn-flat"><i class="fa fa-arrow-right text-muted"></i></button>--%>
                            </div>
                        </div>
                    </div>
                    <!-- /.lockscreen credentials -->

                </div>
                <!-- /.lockscreen-item -->

                <div class="lockscreen-link">
                    <button class="btn btn-primary btn-flat" runat="server" id="bttnSubmit" onserverclick="bttnSubmit_click"><i class="fa fa-lock"></i>  Login</button>
                    <br />
                    <asp:Label ID="lblError" runat="server" Text="" ForeColor="Red"></asp:Label>
                    <%--<a href="login.html">Or sign in as a different user</a>--%>
                </div>
            </div>
            <!-- /.center -->

            <!-- jQuery 2.0.2 -->
            <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
            <!-- Bootstrap -->
            <script src="js/bootstrap.min.js" type="text/javascript"></script>

            <!-- page script -->
            <script type="text/javascript">
                $(function () {
                    startTime();
                    $(".center").center();
                    $(window).resize(function () {
                        $(".center").center();
                    });
                });

                /*  */
                function startTime() {
                    var today = new Date();
                    var h = today.getHours();
                    var m = today.getMinutes();
                    var s = today.getSeconds();

                    // add a zero in front of numbers<10
                    m = checkTime(m);
                    s = checkTime(s);

                    //Check for PM and AM
                    var day_or_night = (h > 11) ? "PM" : "AM";

                    //Convert to 12 hours system
                    if (h > 12)
                        h -= 12;

                    //Add time to the headline and update every 500 milliseconds
                    $('#time').html(h + ":" + m + ":" + s + " " + day_or_night);
                    setTimeout(function () {
                        startTime()
                    }, 500);
                }

                function checkTime(i) {
                    if (i < 10) {
                        i = "0" + i;
                    }
                    return i;
                }

                /* CENTER ELEMENTS IN THE SCREEN */
                jQuery.fn.center = function () {
                    this.css("position", "absolute");
                    this.css("top", Math.max(0, (($(window).height() - $(this).outerHeight()) / 2) +
                            $(window).scrollTop()) - 30 + "px");
                    this.css("left", Math.max(0, (($(window).width() - $(this).outerWidth()) / 2) +
                            $(window).scrollLeft()) + "px");
                    return this;
                }
            </script>

            <%--<div class="form-box" id="login-box">
            <div class="header">Sign In : Dashboard</div>
            <form>
                <div class="body bg-gray">
                    <asp:Label ID="lblError" runat="server" Text="" ForeColor="Red"></asp:Label>
                    <div class="form-group">
                        user name <br />
                        <input type="text" id="txtUserName" runat="server" name="userid" class="form-control" placeholder="User ID" />
                    </div>
                    <div class="form-group">
                        password <br />
                        <input type="password" id="txtPassword" runat="server" name="password" class="form-control" placeholder="Password" />
                    </div>
                </div>
                <div class="footer">
                    <button type="button" id="bttnSubmit" runat="server" onserverclick="bttnSubmit_click" class="btn bg-light-blue btn-block">Sign me in</button>
                    
                </div>
            </form>

            <div class="margin text-center">

            </div>
        </div>
    
        <!-- jQuery 2.0.2 -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="js1/bootstrap.min.js" type="text/javascript"></script>--%>
        </div>
    </form>
</body>
</html>
